// <auto-generated />
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231108110846_mg1")]
    partial class mg1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.BillingDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BillingDetail");

                    b.HasDiscriminator<string>("Type").HasValue("BillingDetail");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DataAccess.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Category 0"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Category 1"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Category 2"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Category 3"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Category 4"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Category 5"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Category 6"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Category 7"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Category 8"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Category 9"
                        });
                });

            modelBuilder.Entity("DataAccess.MainRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MainRoles");
                });

            modelBuilder.Entity("DataAccess.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,10)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name", "Price")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 6,
                            Name = "Product 0",
                            Price = 0m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 7,
                            Name = "Product 1",
                            Price = 5m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 5,
                            Name = "Product 2",
                            Price = 10m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 6,
                            Name = "Product 3",
                            Price = 15m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Name = "Product 4",
                            Price = 20m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 6,
                            Name = "Product 5",
                            Price = 25m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Name = "Product 6",
                            Price = 30m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 9,
                            Name = "Product 7",
                            Price = 35m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 8,
                            Name = "Product 8",
                            Price = 40m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Name = "Product 9",
                            Price = 45m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 8,
                            Name = "Product 10",
                            Price = 50m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            Name = "Product 11",
                            Price = 55m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 4,
                            Name = "Product 12",
                            Price = 60m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            Name = "Product 13",
                            Price = 65m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            Name = "Product 14",
                            Price = 70m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 6,
                            Name = "Product 15",
                            Price = 75m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 6,
                            Name = "Product 16",
                            Price = 80m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 3,
                            Name = "Product 17",
                            Price = 85m
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            Name = "Product 18",
                            Price = 90m
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 1,
                            Name = "Product 19",
                            Price = 95m
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 8,
                            Name = "Product 20",
                            Price = 100m
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 1,
                            Name = "Product 21",
                            Price = 105m
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 5,
                            Name = "Product 22",
                            Price = 110m
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 7,
                            Name = "Product 23",
                            Price = 115m
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 6,
                            Name = "Product 24",
                            Price = 120m
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 3,
                            Name = "Product 25",
                            Price = 125m
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 2,
                            Name = "Product 26",
                            Price = 130m
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 1,
                            Name = "Product 27",
                            Price = 135m
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 9,
                            Name = "Product 28",
                            Price = 140m
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 2,
                            Name = "Product 29",
                            Price = 145m
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 2,
                            Name = "Product 30",
                            Price = 150m
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 4,
                            Name = "Product 31",
                            Price = 155m
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 5,
                            Name = "Product 32",
                            Price = 160m
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 6,
                            Name = "Product 33",
                            Price = 165m
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 4,
                            Name = "Product 34",
                            Price = 170m
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 4,
                            Name = "Product 35",
                            Price = 175m
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 9,
                            Name = "Product 36",
                            Price = 180m
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 9,
                            Name = "Product 37",
                            Price = 185m
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 2,
                            Name = "Product 38",
                            Price = 190m
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 7,
                            Name = "Product 39",
                            Price = 195m
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 4,
                            Name = "Product 40",
                            Price = 200m
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 6,
                            Name = "Product 41",
                            Price = 205m
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 1,
                            Name = "Product 42",
                            Price = 210m
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 9,
                            Name = "Product 43",
                            Price = 215m
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 6,
                            Name = "Product 44",
                            Price = 220m
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 5,
                            Name = "Product 45",
                            Price = 225m
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 2,
                            Name = "Product 46",
                            Price = 230m
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 5,
                            Name = "Product 47",
                            Price = 235m
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 3,
                            Name = "Product 48",
                            Price = 240m
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 5,
                            Name = "Product 49",
                            Price = 245m
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 6,
                            Name = "Product 50",
                            Price = 250m
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 7,
                            Name = "Product 51",
                            Price = 255m
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 1,
                            Name = "Product 52",
                            Price = 260m
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 2,
                            Name = "Product 53",
                            Price = 265m
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 3,
                            Name = "Product 54",
                            Price = 270m
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 2,
                            Name = "Product 55",
                            Price = 275m
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 4,
                            Name = "Product 56",
                            Price = 280m
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 6,
                            Name = "Product 57",
                            Price = 285m
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 7,
                            Name = "Product 58",
                            Price = 290m
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 2,
                            Name = "Product 59",
                            Price = 295m
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 2,
                            Name = "Product 60",
                            Price = 300m
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 3,
                            Name = "Product 61",
                            Price = 305m
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 6,
                            Name = "Product 62",
                            Price = 310m
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 1,
                            Name = "Product 63",
                            Price = 315m
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 5,
                            Name = "Product 64",
                            Price = 320m
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 4,
                            Name = "Product 65",
                            Price = 325m
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 7,
                            Name = "Product 66",
                            Price = 330m
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 1,
                            Name = "Product 67",
                            Price = 335m
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 5,
                            Name = "Product 68",
                            Price = 340m
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 3,
                            Name = "Product 69",
                            Price = 345m
                        },
                        new
                        {
                            Id = 71,
                            CategoryId = 5,
                            Name = "Product 70",
                            Price = 350m
                        },
                        new
                        {
                            Id = 72,
                            CategoryId = 3,
                            Name = "Product 71",
                            Price = 355m
                        },
                        new
                        {
                            Id = 73,
                            CategoryId = 6,
                            Name = "Product 72",
                            Price = 360m
                        },
                        new
                        {
                            Id = 74,
                            CategoryId = 1,
                            Name = "Product 73",
                            Price = 365m
                        },
                        new
                        {
                            Id = 75,
                            CategoryId = 6,
                            Name = "Product 74",
                            Price = 370m
                        },
                        new
                        {
                            Id = 76,
                            CategoryId = 2,
                            Name = "Product 75",
                            Price = 375m
                        },
                        new
                        {
                            Id = 77,
                            CategoryId = 7,
                            Name = "Product 76",
                            Price = 380m
                        },
                        new
                        {
                            Id = 78,
                            CategoryId = 7,
                            Name = "Product 77",
                            Price = 385m
                        },
                        new
                        {
                            Id = 79,
                            CategoryId = 7,
                            Name = "Product 78",
                            Price = 390m
                        },
                        new
                        {
                            Id = 80,
                            CategoryId = 9,
                            Name = "Product 79",
                            Price = 395m
                        },
                        new
                        {
                            Id = 81,
                            CategoryId = 9,
                            Name = "Product 80",
                            Price = 400m
                        },
                        new
                        {
                            Id = 82,
                            CategoryId = 3,
                            Name = "Product 81",
                            Price = 405m
                        },
                        new
                        {
                            Id = 83,
                            CategoryId = 6,
                            Name = "Product 82",
                            Price = 410m
                        },
                        new
                        {
                            Id = 84,
                            CategoryId = 5,
                            Name = "Product 83",
                            Price = 415m
                        },
                        new
                        {
                            Id = 85,
                            CategoryId = 6,
                            Name = "Product 84",
                            Price = 420m
                        },
                        new
                        {
                            Id = 86,
                            CategoryId = 8,
                            Name = "Product 85",
                            Price = 425m
                        },
                        new
                        {
                            Id = 87,
                            CategoryId = 4,
                            Name = "Product 86",
                            Price = 430m
                        },
                        new
                        {
                            Id = 88,
                            CategoryId = 4,
                            Name = "Product 87",
                            Price = 435m
                        },
                        new
                        {
                            Id = 89,
                            CategoryId = 5,
                            Name = "Product 88",
                            Price = 440m
                        },
                        new
                        {
                            Id = 90,
                            CategoryId = 6,
                            Name = "Product 89",
                            Price = 445m
                        },
                        new
                        {
                            Id = 91,
                            CategoryId = 8,
                            Name = "Product 90",
                            Price = 450m
                        },
                        new
                        {
                            Id = 92,
                            CategoryId = 3,
                            Name = "Product 91",
                            Price = 455m
                        },
                        new
                        {
                            Id = 93,
                            CategoryId = 4,
                            Name = "Product 92",
                            Price = 460m
                        },
                        new
                        {
                            Id = 94,
                            CategoryId = 2,
                            Name = "Product 93",
                            Price = 465m
                        },
                        new
                        {
                            Id = 95,
                            CategoryId = 3,
                            Name = "Product 94",
                            Price = 470m
                        },
                        new
                        {
                            Id = 96,
                            CategoryId = 3,
                            Name = "Product 95",
                            Price = 475m
                        },
                        new
                        {
                            Id = 97,
                            CategoryId = 8,
                            Name = "Product 96",
                            Price = 480m
                        },
                        new
                        {
                            Id = 98,
                            CategoryId = 7,
                            Name = "Product 97",
                            Price = 485m
                        },
                        new
                        {
                            Id = 99,
                            CategoryId = 5,
                            Name = "Product 98",
                            Price = 490m
                        },
                        new
                        {
                            Id = 100,
                            CategoryId = 4,
                            Name = "Product 99",
                            Price = 495m
                        });
                });

            modelBuilder.Entity("DataAccess.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("DataAccess.RoleMainRole", b =>
                {
                    b.Property<int>("MainRoleId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("MainRoleId", "RoleId");

                    b.ToTable("RoleMainRoles");
                });

            modelBuilder.Entity("DataAccess.BankAccount", b =>
                {
                    b.HasBaseType("DataAccess.BillingDetail");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("BA");
                });

            modelBuilder.Entity("DataAccess.CreditCard", b =>
                {
                    b.HasBaseType("DataAccess.BillingDetail");

                    b.Property<string>("CartType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("CA");
                });

            modelBuilder.Entity("DataAccess.Product", b =>
                {
                    b.HasOne("DataAccess.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DataAccess.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
